image: docker:latest

variables:
  #MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  #MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  RUNNER_ENV: "DOCKER_TLS_CERTDIR="

stages:
  - tests
  #- build
 # - test
 # - deploy

test_app:
  stage: tests
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - cd src/main/docker
    - docker-compose up -d db_api_betgain tests
   # - docker-compose up --build --force-recreate --no-deps tests
    - testsSuccess=$(docker inspect tests --format='{{.State.ExitCode}}')
    - if [ $testsSuccess -eq "0" ];
      then
      exit 0;
      else
      exit 1;
      fi
    #building:
 # stage: build
 # script:


#testing:
  #stage: test
 # script:
  #  - make tests

#staging:
#  type: deploy
#  stage: deploy
#  image: ruby:latest
 # script:
 #   - apt-get update -yq
  #  - apt-get install -y ruby-dev
   # - gem install dpl
    # - apt-get install -yqq ruby ruby-dev nodejs --silent
   # - dpl --provider=heroku --app=aqueous-savannah-31805 --api-key=$HEROKU_STAGING_API_KEY
