image: alpine:3.7

variables:
  #MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  #MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - prepare
  - build
  - test
 # - deploy

update:
  stage: prepare
  script:
    - apt-get update
    - apt-get install make
    - curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose --version

building:
  stage: build
  script:
    - ls
    - make install

testing:
  stage: test
  script:
    - make tests

#staging:
#  type: deploy
#  stage: deploy
#  image: ruby:latest
 # script:
 #   - apt-get update -yq
  #  - apt-get install -y ruby-dev
   # - gem install dpl
    # - apt-get install -yqq ruby ruby-dev nodejs --silent
   # - dpl --provider=heroku --app=aqueous-savannah-31805 --api-key=$HEROKU_STAGING_API_KEY
